config/routes.rb
Rails.application.routes.draw do

  resources :race_groups, only: [ :show ]



  root to: 'pages#home'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :races, only: [ :index, :show ] do
    resources :race_groups, only: [ :create ] do
      resource :group_memberships, only: [ :create ]
    end
  end

  resources :group_memberships, only: [] do
    member do
      patch :confirm
      patch :cancel
    end
  end

  namespace :account do
    resource :profile, only: [ :show ]

    resources :races, only: [ :index ] do
      member do
        patch :confirm
      end
    end
  end

  # static pages
  get 'styleguide', to: 'pages#styleguide'

end

app/models/race.rb
class Race < ApplicationRecord
  #database
  has_many :race_groups, dependent: :destroy
  has_many :users, through: :race_groups
  has_many :group_memberships, through: :race_groups
  has_many :members, through: :group_memberships, source: :user, class_name: "User"
  has_many :race_sports, dependent: :destroy
  has_many :sports, through: :race_sports

  #photo uploader
  mount_uploader :picture, PhotoUploader
  mount_uploader :trail_map_picture, PhotoUploader

  #validations
  validates :name, uniqueness: { scope: :date}, presence: true
  validates :date, presence: true
  validates :location, presence: true
  validates :price, presence: true

  def calculate_total_distance!
    self.total_distance = self.race_sports.pluck(:distance).reduce(:+)
  end

  geocoded_by :location
  after_validation :geocode, if: :location_changed?

  # scope :location(params), -> do
  #   where ("location Ilike %#{params}%" )
  # # scope :sport, -> (sport) { where "location like?", "%#{params[:search][:sport_name[]]}%""}
  # end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @sport_names = params[:search][:sports_name]

    if @sport_names.nil?
      @races = Race.all
    else
      @races = Race.joins(:sports).where("sports.name IN (?)", @sport_names).distinct
    end

    unless params[:search][:place].nil?
      @races = @races.where("location ILike ?", "%#{params[:search][:place]}%").where.not(latitude: nil, longitude: nil)
    end

    if params[:search][:date] != ""
      @date_search = Date.parse(params[:search][:date])
      @races = @races.where(date: @date_search)
    end

    if @races
      @place_markers_hash = Gmaps4rails.build_markers(@races) do |race, marker|
        marker.lat        race.latitude
        marker.lng        race.longitude
        marker.title      race.name
        marker.infowindow render_to_string(partial: "/races/map_infowindow", locals:  { race: race })
      end
    end
    @sports = Sport.all
  end

  def show
    @race = Race.find(params[:id])

    if current_user
      @group_membership = @race.group_memberships.where(user_id: current_user).first
      # @race_group = @group_membership.race_group if @group_membership
      # @race_group = @race.race_groups.joins(:group_memberships).where("group_memberships.user_id = ?", current_user.id).first
      return redirect_to race_group_path(@group_membership.race_group ) if @group_membership
    end

    @sports = Sport.all
  end
end

app/views/races/_map_infowindow.html.erb
<div class="row">
  <h3><%= race.name %></h3>
  <p><%= race.date %></p>
  <%= link_to race_path(race) do%>
  <%= image_tag race.picture %>
  <% end %>
</div>

app/views/races/index.html.erb
<div class="<%= sport_cover_css_class(@sport_names) %>">
  <div class="container">
    <div class= "slogan">
      <h1 class="title">VOICI TA<br>LISTE DE COURSES</h1>
    </div>
  </div>
</div>
<!-- <div class="box">
  <%= link_to root_path, class: "link-back-root" do%>
    <i class="fa fa-arrow-circle-left" aria-hidden="true"></i>
    <span class= "link-back-root-text">Trouve une autre course</span>
  <% end %> -->
<div class="results-wrapper-index">
  <div class="container_index-full">
    <div class="row">
      <div class="col-xs-6 col-sm-8 col-md-8">
        <div class="row">
          <% @races.each do |race| %>
            <div class="col-xs-12 col-sm-6 col-md-4">
              <%= link_to race_path(race) do %>
                <div class="card-index" style="<%= "background-image: url('#{cl_image_path race.picture, effect: "grayscale"}'); background-size: cover;"%>">
                  <div class="card-date-J-index"> J - <%=(race.date - Date.today).to_i %></div>
                  <div class="card-level-index">
                  <% if race.level == "débutant" %>
                    <span class="label label-success">Débutant</span>
                  <% elsif race.level == "intermédiaire" %>
                    <span class="label label-warning">Intermédiaire</span>
                  <% elsif race.level == "expert" %>
                    <span class="label label-danger">Expert</span>
                  <% end %>
                  </div>
                  <div class="card-description-race-index text-center" style="<%= "background: #{multi_linear_background_for(race.sports)};"%>">
                      <p><%= l(race.date, format: '%d %B %Y') %></p>
                      <h2><%= race.name.upcase %></h2>
                      <h4><%= race.total_distance %> km</h4>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

        <div class="col-xs-6 col-sm-4 col-md-4">
          <div id="map" style="width: 100%; height: 700px;">
          </div>

          <% content_for(:after_js) do %>
            <script>
              $(document).ready(function() {
                var handler = Gmaps.build('Google');
                handler.buildMap({ internal: { id: 'map' } }, function() {
                  markers = handler.addMarkers(<%= raw @place_markers_hash.to_json %>);
                  console.log(markers);
                  handler.bounds.extendWith(markers);
                  handler.fitMapToBounds();
                  if (markers.length == 0) {
                    handler.getMap().setZoom(10);
                  } else if (markers.length == 2) {
                    handler.getMap().setZoom(8);
                  }
                });
              });
            </script>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/races/show.html.erb
<% content_for :meta_title, "#{@race.name} - Friends Challenge" %>
<% content_for :meta_description, truncate(@race.description, length: 200) %>
<%= render 'shared/race_show_base', race: @race, race_group: @race_group, group_membership: @group_membership, view_mode: :race %>