config/routes.rb
Rails.application.routes.draw do

  resources :race_groups, only: [ :show ]



  root to: 'pages#home'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :races, only: [ :index, :show ] do
    resources :race_groups, only: [ :create ] do
      resource :group_memberships, only: [ :create ]
    end
  end

  resources :group_memberships, only: [] do
    member do
      patch :confirm
      patch :cancel
    end
  end

  namespace :account do
    resource :profile, only: [ :show ]

    resources :races, only: [ :index ] do
      member do
        patch :confirm
      end
    end
  end

  # static pages
  get 'styleguide', to: 'pages#styleguide'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="navbar-item">   </div>
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo2.jpg" %>
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right navbar-item">

    <!-- Search form -->
    <!-- <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <!-- <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %> -->

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.facebook_picture_url.nil? %>
            <%= image_tag "http://lorempixel.com/50/50/" , class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
            <% else %>
            <%= image_tag current_user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <!-- <li> -->
              <!--   <%= link_to "#" do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
                <% end %>
              </li> -->
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          <% end %>
        </div>
      </div>

    <% else %>
      <!-- <%= link_to t(".top_call_to_action", default: "Mes Courses"), "#", class: "my_races_access" %> -->
      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "LOGIN"), new_user_session_path, class: "btn-search-small" %>

    <% end %>

    <!-- Button (call-to-action) -->

  </div>

  <!-- Dropdown list appearing on mobile only -->
<!--   <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div> -->
</div>

app/views/shared/_race_show_base.html.erb
<% if view_mode == :race_group && group_membership.nil? %>
  <div class="banner-interested">
    <div class="text-interested">
       <p><%= race_group.user.first_name %> compte sur toi pour rejoindre sa team !</p>
    </div>
  </div>
<% end %>
<div class="container-full">
  <div class="row">
    <div class="<%= view_mode == :race ? 'col-xs-12 col-md-12' : 'col-xs-9 col-md-10' %>">
      <div class="raceshow-wrapper" style="<%= "background-image: #{multi_linear_background_for(race.sports)}, url('#{cl_image_path @race.picture, effect: "grayscale"}'); background-size: cover;" %>">
        <div class="event-info">
            <p><%= l(race.date, format: '%d %B %Y') %></p>
            <h1 id="event-title"><%= race.name.upcase %></h1>
            <h3 class="bulletpoints"><%= race.total_distance %> km - <%= race.location%><%= link_to "En savoir +", race.official_event_url, class: "link" %></h3>
        </div>
        <div class="level-sticker">
          <% if race.level == "débutant" %>
            <span class="label label-success">Débutant</span>
          <% elsif race.level == "intermédiaire" %>
            <span class="label label-warning">Intermédiaire</span>
          <% elsif race.level == "expert" %>
            <span class="label label-danger">Expert</span>
          <% end %>
        </div>
        <div class="my-status">
          <% if view_mode == :race_group && group_membership %>
            <% if group_membership.status == "Intéressé" %>
              <span class="label label-primary">Je suis intéressé</span>
            <% elsif group_membership.status == "Confirmé" %>
              <span class="label label-success">J'ai confirmé</span>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <% if view_mode == :race_group %>
      <div class="col-xs-3 col-md-2">
        <div class="race-group-friends">
          <ul class="list-unstyled">
            <% @memberships.each do |membership| %>
              <li>
                <div class="member-info">
                  <% if membership.user.facebook_picture_url.nil? %>
                    <%= image_tag "http://lorempixel.com/50/50/" %>
                  <% else %>
                    <%= image_tag membership.user.facebook_picture_url, class: "fb-image" %>
                  <% end %>
                  <div class="name-and-status">
                    <h4 style="margin-bottom: 3px"><%= membership.user.first_name %></h4>
                    <p><%= membership.status %></p>
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
        <% if group_membership %>
          <div class="sharing text-center">
            <p class="info-sharing-link">CHAUFFE TES POTES</p>
            <div class="sharing-options">
              <ul class="list-inline">
                <li>
                  <%= link_to "http://www.facebook.com/share.php?u=#{race_group_url(race_group)}", onclick: "javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;" do %>
                    <i class="fa fa-facebook-official sharing-buttons" aria-hidden="true"></i>
                  <% end %>
                </li>
                <li>
                  <%= link_to race_group_url(race_group) do %>
                    <i class="fa fa-link sharing-buttons" aria-hidden="true"></i>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
</div>
<div class="trail-map-and-interested-wrapper">

    <div class="row">
      <div class="col-xs-12 col-md-offset-2 col-md-4">
        <div class="trail-map">
            <%= cl_image_tag race.trail_map_picture %>
        </div>
      </div>
      <div class="col-xs-12 col-md-4">
      <div class="interest-and-description text-center">
        <% if view_mode == :race %>
            <% if group_membership %><!-- current user already member -->
              <%= link_to "VOIR MON GROUPE", race_group_path(race_group), class: "btn-interested" %>
            <% else %>
              <%= link_to "CA M'INTÉRESSE !", race_race_groups_path(race), method: :post, class: "btn-interested"%>
            <% end %>
          </div>
        <% else %><!-- race group view -->
          <% if group_membership.nil? %><!-- current user NOT member yet -->
            <%= link_to "CA M'INTÉRESSE !", race_race_group_group_memberships_path(race.id, race_group.id), method: :post, class: "btn-interested"%>
          <% elsif group_membership.status == "Intéressé" %><!-- current user interested -->
            <%= link_to "JE CONFIRME !", confirm_group_membership_path(group_membership), method: :patch, class: "btn-interested"%>
          <% elsif group_membership.status == "Confirmé" %>
            <%= link_to "JE DOIS ANNULER", cancel_group_membership_path(group_membership), method: :patch, class: "btn-interested"%>
          <% end %>
        <% end %>
        <div class="description-text">
          <%= race.description %>
        </div>
      </div>
    </div>
  </div>
</div>