config/routes.rb
Rails.application.routes.draw do

  resources :race_groups, only: [ :show ]



  root to: 'pages#home'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :races, only: [ :index, :show ] do
    resources :race_groups, only: [ :create ] do
      resource :group_memberships, only: [ :create ]
    end
  end

  resources :group_memberships, only: [] do
    member do
      patch :confirm
      patch :cancel
    end
  end

  namespace :account do
    resource :profile, only: [ :show ]

    resources :races, only: [ :index ] do
      member do
        patch :confirm
      end
    end
  end

  # static pages
  get 'styleguide', to: 'pages#styleguide'

end

app/views/pages/home.html.erb
<div class="wrapper-cover-picture">
  <div class="container">
    <div class= "slogan">
      <h1 class="title">TROUVE TA COURSE, <br>INVITE TES POTES.</h1>
    </div>
  </div>
</div>
<div class="box">
  <div class= "form-group form-items">
    <%= form_tag races_path, method: :get do %>
      <div class="form-item1">
        <% @sports.each do |sport| %>
          <%= label_tag '', nil, class: "buttons-sports", style: "background-image: linear-gradient(-225deg, #{linear_background_for(sport)} 60%, rgba(255, 255, 255, 0.5) 100%), url('#{image_path picture_path_for(sport)}'); background-size: cover;" do %>
            <%= check_box_tag "search[sports_name][]", sport.name, nil, class: "hide_checkbox" %>
            <p class="sports-label"><%= placeholder_for(sport) %></p>
          <% end %>
        <% end %>
      </div>
      <div class="form-item2">
        <%= search_field :search, :place, placeholder: 'OÙ ?', class: "search-form", style: "text-align: center" %>
        <%= date_field :search, :date, class: "search-form", style: "text-align: center", id: "datepicker", placeholder: "QUAND ?" %>
      </div>
      <div class="form-item3 text-center">
        <%= submit_tag "GO !", class: "btn-search"%>
      </div>
    <% end %>
  </div>
</div>

<% content_for(:after_js) do %>
  <script>
    var picker = new Pikaday({
                              field: $('#datepicker')[0],
                              position: "top left" });
  </script>
<% end %>